service: service:VLLM
name: phi3
version: 3.8b-instruct-fp16-bb8b
bentoml_version: 1.3.10
creation_time: '2024-10-30T10:50:05.318999+00:00'
labels:
  model_name: microsoft/Phi-3-mini-4k-instruct
  openllm_alias: 3.8b,3.8b-mini,3.8b-mini-instruct-4k-fp16
  platforms: linux
  source: https://github.com/bentoml/openllm-models/tree/main/src/vllm-chat
models: []
entry_service: phi3
services:
- name: phi3
  service: ''
  models: []
  dependencies: []
  config:
    name: phi3
    resources:
      gpu: 1
      gpu_type: nvidia-rtx-3060
    traffic:
      timeout: 300
envs: []
schema:
  name: phi3
  type: service
  routes:
  - name: generate
    route: /generate
    batchable: false
    input:
      properties:
        prompt:
          default: what is this?
          title: Prompt
          type: string
      title: Input
      type: object
    output:
      title: IORootModel[str]
      type: string
      is_stream: true
      media_type: text/event-stream
    is_task: false
  - name: generate_with_image
    route: /generate_with_image
    batchable: false
    input:
      properties:
        prompt:
          default: what is this?
          title: Prompt
          type: string
        image:
          default: null
          title: Image
          format: image
          type: file
      title: Input
      type: object
    output:
      title: IORootModel[str]
      type: string
      is_stream: true
      media_type: text/event-stream
    is_task: false
spec: 1
runners: []
apis: []
docker:
  distro: debian
  python_version: '3.9'
  cuda_version: null
  env: null
  system_packages: null
  setup_script: null
  base_image: null
  dockerfile_template: null
python:
  requirements_txt: ./requirements.txt
  packages: null
  lock_packages: true
  pack_git_packages: true
  index_url: null
  no_index: null
  trusted_host: null
  find_links: null
  extra_index_url: null
  pip_args: null
  wheels: null
conda:
  environment_yml: null
  channels: null
  dependencies: null
  pip: null
